### PR TITLE
port to kodi 19.x

### LINKED ISSUE #29: add kodi 19.x support
`kodi` has switched to `python3` from version `19.x` onward. When I try to install this plugin onto `kodi` version `19.x` I get the following error:

> 2020-11-30 23:42:30.898 T:14978   ERROR <general>: CAddonInstallJob[plugin.program.steam.library]: The dependency on xbmc.python version 2.19.0 could not be satisfied.

If we're lucky it might be as simple as updating the `addon.xml` file to mention `python3` instead of `python2`.

### PR DESCRIPTION
**Pull request by aanderse**
With these changes the plugin loads. I haven't had a chance to test that games actually launch yet, though.

resolves #29

### CODE REVIEW

**Comment by aanderse** [comment]
Tested launching games. Everything looks fine to me.

**Review by AmineI — COMMENTED** [review]
The code changes you made are looking good ! I'm not able to test this out yet however, I'll try to  do that on Windows when I can

**Comment by aanderse** [comment]
Great! Thanks @AmineI.

**Comment by AmineI** [comment]
On Windows, with a clean Kodi 19 installation, the plugin works fine now.

However, when migrating from V18 to V19 (thus keeping this plugin's previous settings and data), if I try to open one of the games view on my machine, the plugin crashes while reading from the existing cache with a `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3519 : ordinal not in range(128)`.

It looks like Python 2/Python 3 default encodings are different, but I can't seem to override the used decoder myself since the error happens in the "request-cache" Kodi module we depend on, which deals with updating and reading the caches.

The workaround I used for that issue was to just delete the previous cache databases, (we can do that with a simple call to `delete_cache()` in `main.py` when upgrading the version) - they are then recreated with the proper encoding. Does that sounds good to you ? Do you encounter the same issue on Linux as well?

**Comment by aanderse** [comment]
Thanks for your help on this! I hadn't tried an upgrade yet, so your solution sounds good.

**Comment by AmineI** [comment]
Apologies, I wasn't able to get back to this since then, thanks for merging. I'll try to implement the upgrade path this week.

**Pull request merged**
